name: gemini-desktop
summary: Gemini
description: |
  Unofficial Web app for Google Gemini providing the desktop user
  experience you would expect on Ubuntu or any other Linux desktop

  For microphone access you need to connect the audio-record interface:

     sudo snap connect gemini-desktop:audio-record

grade: stable
confinement: strict
base: core24
contact: https://github.com/kenvandine/gemini-desktop/issues
issues: https://github.com/kenvandine/gemini-desktop/issues
website: https://github.com/kenvandine/gemini-desktop
license: GPL-3.0+
icon: icon512.png

platforms:
  amd64:
  arm64:
compression: lzo

parts:
  gemini-desktop:
    plugin: nil
    source: .
    build-packages:
      - npm
      - git
    override-build: |
      craftctl set version=$(git describe --tags --abbrev=10)
      npm install
      npm run build
      mkdir -p $SNAPCRAFT_PART_INSTALL/unpacked
      cp $SNAPCRAFT_PROJECT_DIR/com.github.kenvandine.gemini-desktop.desktop $SNAPCRAFT_PART_INSTALL/unpacked/
      cp $SNAPCRAFT_PROJECT_DIR/icon.png $SNAPCRAFT_PART_INSTALL/
      mv dist/linux*-unpacked/* $SNAPCRAFT_PART_INSTALL/unpacked 
    prime:
      - unpacked
      - icon.png
      - -*/chrome-sandbox
      - -*/resources/app.asar.unpacked/node_modules/sharp/vendor/lib
      - -*/resources/app.asar.unpacked/node_modules/sharp/vendor/include

  cleanup:
    after: [ gemini-desktop ]
    plugin: nil
    build-snaps: [ gnome-46-2404 ]
    override-prime: |
        set -eux
        cd /snap/gnome-46-2404/current
        find . -type f,l -exec rm -f $SNAPCRAFT_PRIME/{} \;

plugs:
  shmem:
    interface: shared-memory
    private: true

apps:
  gemini-desktop:
    extensions: [gnome]
    desktop: unpacked/com.github.kenvandine.gemini-desktop.desktop
    command: unpacked/gemini-desktop --use-tray-icon --no-sandbox --disable-seccomp-filter-sandbox
    plugs:
      - shmem
      - network
      - audio-playback
      - audio-record
      - unity7
    environment:
      GTK_USE_PORTAL: "1"
      TMPDIR: $XDG_RUNTIME_DIR
